import json
import re

filepath = r"C:\Users\Ota\Documents\Portable Applications\(Python Scripts)\gel_blaster_compare\src\blasters_data.json"

with open(filepath, 'r', encoding='utf-8') as f:
    blasters = json.load(f)

# Clear old intel
for blaster in blasters:
    if 'cross_referenced_specs' in blaster and 'notes' in blaster['cross_referenced_specs']:
        blaster['cross_referenced_specs']['notes'] = ""

def generate_intel(title, cat):
    title = title.upper()
    
    # ---------------- RIFLES ----------------
    if "JINGJI V6" in title:
        return (
            "📌 **Designation**: 精击 / JingJi V6 ASI体系\n"
            "🔍 **Tieba Consensus**: The V6 gearbox architecture is drastically improved over the V4. Factory shimming is pristine out of the box.\n"
            "⚠️ **Bilibili Tech Warning**: The integrated SVT Mosfet utilizes optical sensors to detect sector gear cycling. Extremely prone to fouling if shattered gel debris enters the optical path. Strictly utilize ultra-hard dehydrated gels (e.g., LDT Warinterest Milky Whites)."
        )
    elif "JINGJI SLR B56" in title:
        return (
            "📌 **Designation**: 精击 / JingJi SLR B56\n"
            "🔍 **Tieba Consensus**: Widely recognized as the gold standard for high-end nylon AR platforms. Features a fully functional bolt hold-open mechanism that mimics real steel.\n"
            "📸 **Xiaohongshu Vibe**: The absolute darling of tactical cosplay (战术造型). Heavily featured in 'OOTD' tactical loadout shoots due to its 1:1 realism and matte nylon finish.\n"
            "⚠️ **Bilibili Tech Warning**: The secondary tappet return spring in the v5 gearbox is occasionally too stiff from the factory, which can cause magazine feeding geometry issues when pushed past 25 RPS on heavy 11.1v batteries."
        )
    elif "JINGJI SR16" in title:
        return (
            "📌 **Designation**: 精击 / JingJi SR16 分体波箱版\n"
            "🔍 **Tieba Consensus**: Peak 'Enthusiast Tier'. The metal Split-Gearbox (分体波) makes spring swaps and piston maintenance an absolute breeze compared to monolithic boxes.\n"
            "⚖️ **Zhihu Context**: Frequently discussed on Zhihu as the line where 'toys' become complicated hardware, sparking debates on the escalating cost of the hobby in the mainland.\n"
            "⚠️ **Bilibili Tech Warning**: Under 11.1v cyclical stress, the cast metal piston rack must be upgraded to a full CNC steel rack before attempting M110 or M120 spring pressures."
        )
    elif "JINGJI SLR CQB" in title:
        return (
            "📌 **Designation**: 精击 / JingJi SLR 极短版\n"
            "🔍 **Tieba Consensus**: Phenomenal CQB maneuverability; perfectly balanced weight distribution.\n"
            "⚠️ **Bilibili Tech Warning**: If purchasing the 'Clear/Transparent' (透明) edition, absolutely do not install heavy springs. Polycarbonate is notoriously brittle and will crack around the gearbox mounting pins under intense vibration."
        )
    elif "JINGJI PDX" in title:
        return (
            "📌 **Designation**: 精击 / JingJi PDX (咆哮者)\n"
            "🔍 **Tieba Consensus**: Nicknamed 'The Screamer' due to the massive pneumatic 'bang' generated by the short barrel.\n"
            "⚠️ **Bilibili Tech Warning**: Because the barrel is absurdly short, you MUST utilize a heavily ported Type-3 cylinder. A full cylinder will result in massive volumetric over-pressurization, instantly shattering gels inside the T-piece."
        )
    elif "CYMA HK416" in title:
        return (
            "📌 **Designation**: 司马 / CYMA HK416A5\n"
            "🔍 **Tieba Consensus**: Classic V2 reliability wrapped in dense, aggressive exterior nylon. Out-competes JingJi on pure structural rigidity.\n"
            "⚠️ **Bilibili Tech Warning**: Factory metal gears are bomb-proof on 7.4V. However, prolonged full-auto bursts on 11.1V will eventually arc the proprietary trigger switch contacts—a standard inline Mosfet is a mandatory reliability mod."
        )
    elif "CYMA AK47" in title and "ESHOOTER" in title.upper():
        return (
            "📌 **Designation**: 司马 / CYMA AK47 Eshooter数字版\n"
            "🔍 **Tieba Consensus**: The undisputed king of the AK V3 market. The Eshooter digital trigger unit completely solves traditional V3 contact burnouts.\n"
            "⚠️ **Bilibili Tech Warning**: Mechanically flawless, but aesthetically lacking—the faux-wood polymer feels decidedly hollow. Most purists immediately rip the furniture off for real-wood conversion kits (真木修饰套件)."
        )
    elif "CYMA AK47" in title:
        return (
            "📌 **Designation**: 司马 / CYMA AK47 标准版\n"
            "🔍 **Tieba Consensus**: Excellent workhorse AK. Features nylon external furniture and standard V3 internal contacts.\n"
            "⚠️ **Bilibili Tech Warning**: Standard mechanical switch block inside. Do not spam semi-auto on 11.1v batteries or the internal trigger sled will eventually lock up and arc the contacts."
        )
    elif "CYMA M4" in title and "ESHOOTER" in title.upper():
        return (
            "📌 **Designation**: 司马 / CYMA M4 V2 Eshooter旗舰版\n"
            "🔍 **Tieba Consensus**: The highest possible factory spec for the CYMA M4. The pre-installed Eshooter Optical board allows for pre-cocking and binary triggers.\n"
            "⚠️ **Bilibili Tech Warning**: Because optical sensors detect sector gear cycling, excessive use of wet/oily gel balls will splatter liquid onto the sensor board inside the gearbox, blinding the Eshooter and causing immediate runaway full-auto malfunction. Keep it dry."
        )
    elif "CYMA M4" in title:
        return (
            "📌 **Designation**: 司马 / CYMA M4 标准金属齿版\n"
            "🔍 **Tieba Consensus**: Universally recommended across Chinese forums as the ultimate budget 'First Blaster'. Iterative generational improvements have eliminated any old brittle tappet plate issues.\n"
            "⚠️ **Bilibili Tech Warning**: Re-greasing the cylinder and checking the factory O-ring for absolute air seal will usually yield a free 20 FPS bump due to inconsistent factory lubrication."
        )
    elif "CYMA SCAR" in title:
        return (
            "📌 **Designation**: 司马 / CYMA SCAR-L\n"
            "🔍 **Tieba Consensus**: Dominates the budget SCAR market. The V2/V3 hybrid metal gearbox punches far above its price bracket.\n"
            "⚠️ **Bilibili Tech Warning**: Be extremely gentle with the folding stock mechanism. The thin-gauge battery wires run directly through the hinge, and repeatedly slamming it shut will inevitably sever the harness."
        )
    elif "CYMA G36" in title:
        return (
            "📌 **Designation**: 司马 / CYMA G36\n"
            "🔍 **Tieba Consensus**: An ergonomic masterpiece with a gorgeous monolithic top rail.\n"
            "⚠️ **Bilibili Tech Warning**: The V3 gearbox is buried under numerous exterior retention plates, making maintenance extremely tedious. Magazine feeding tubes occasionally require light internal sanding to clear 7.5mm hard gels."
        )
    elif "CYMA MP5" in title:
        return (
            "📌 **Designation**: 司马 / CYMA MP5\n"
            "🔍 **Tieba Consensus**: Beloved by the Chinese CQB speed-soft community. The 'HK Slap' is natively supported.\n"
            "⚠️ **Bilibili Tech Warning**: Over-slapping the nylon charging handle will inevitably snap it off. The battery compartment housed inside the front handguard is famously cramped, requiring exact ultra-thin 11.1V stick batteries."
        )
    elif "ALPHA KING AK12" in title:
        return (
            "📌 **Designation**: 阿尔法国王 / AKA AK12\n"
            "🔍 **Tieba Consensus**: Peak stamped-steel realism. The finish legitimately rivals real-steel manufacturing. Features a massive internal pneumatic blowback unit (回膛).\n"
            "⚠️ **Bilibili Tech Warning**: Running 11.1V with the blowback actively engaged is a death sentence for the piston rack. The sheer kinetic shock of cyclical recoil on 3S voltages will shear the teeth."
        )
    elif "ALPHA KING PPK20" in title:
        return (
            "📌 **Designation**: 阿尔法国王 / AKA PPK20\n"
            "🔍 **Tieba Consensus**: A stunningly hefty V3 aluminum architecture. Tieba modders extract supreme accuracy from its tight-bore factory barrel.\n"
            "⚠️ **Bilibili Tech Warning**: The same mechanical blowback warnings apply—deactivate the recoil linkages before pushing rate-of-fire boundaries."
        )
    elif "XYL GC16" in title:
        return (
            "📌 **Designation**: 小月亮 / XYL GC16 Wild Hog\n"
            "🔍 **Tieba Consensus**: Externally beautiful aggressive CNC styling.\n"
            "⚠️ **Bilibili Tech Warning**: CRITICAL DEFECT. Bilibili tech channels universally document that the factory XYL Mosfet is highly prone to self-immolation (烧板) on high-discharge 11.1V batteries. Ripping it out for a Perun or T238 is strictly advised."
        )
    elif "E&C M16" in title:
        return (
            "📌 **Designation**: 东鹤 / E&C (East & Crane) M16\n"
            "🔍 **Tieba Consensus**: Sourced from direct Airsoft 1:1 CNC shells, granting it unparalleled exterior intimidation and weight.\n"
            "⚠️ **Bilibili Tech Warning**: The heavy LDX gearbox operates extremely sluggishly on basic 7.4V due to stiff factory springs and high-torque Neodymium motors. 11.1V is mandatory to wake the system up, but ensure Angle of Engagement (AOE) is corrected first."
        )
    elif "E&C STRIKE INDUSTRIES" in title or "E&C N4" in title or "E&C SAI" in title or "E&C JW TTI" in title:
        return (
            "📌 **Designation**: 东鹤 / E&C 旗舰级电波\n"
            "🔍 **Tieba Consensus**: The absolute crown jewels of the E&C lineup. Features breathtaking ceramic-coated CNC receivers.\n"
            "📸 **Xiaohongshu Vibe**: The John Wick TTI and N4 DEVGRU models are heavily fetishized by streetwear/tactical fashion accounts. They exist largely as high-end photography props for urban techwear cosplayers rather than skirmish tools.\n"
            "⚠️ **Bilibili Tech Warning**: The skeletal aluminum receivers amplify gearbox noise to insane levels. Shimming must be absolute perfection, otherwise the blaster will screech mechanically during full-auto fire."
        )
    elif "SIJUN SIG MCX" in title:
        return (
            "📌 **Designation**: 司骏 / SiJun MCX\n"
            "🔍 **Tieba Consensus**: The premier MCX replica on mainland forums. The nylon formulation favors raw impact resistance over absolute rigidness.\n"
            "⚠️ **Bilibili Tech Warning**: The proprietary SJ V2 gearbox houses cast-metal gears but utilizes a fragile nylon piston. Prolonged 11.1v bursts will instantly strip the piston teeth. Upgrade the rack immediately."
        )
    elif "LEHUI HK417" in title:
        return (
            "📌 **Designation**: 乐辉 / LeHui HK417\n"
            "🔍 **Tieba Consensus**: A massive, intimidating support platform favored for outdoor mil-sim operations.\n"
            "⚠️ **Bilibili Tech Warning**: The V2 custom gearbox is painfully complex due to dummy bolt linkages. Running 11.1V on factory internals is highly discouraged, as the proprietary LeHui tappet plates are notorious for snapping under stress."
        )
    elif "LEHUI SIG MPX" in title:
        return (
            "📌 **Designation**: 乐辉 / LeHui MPX\n"
            "🔍 **Tieba Consensus**: Solid, reliable 7.4V CQB backup platform.\n"
            "⚠️ **Bilibili Tech Warning**: Despised by mainland speed-tuners because it uses a proprietary cylinder volume layout. This physically prevents the installation of standard high-volume air seal parts for FPS boosting."
        )
    elif "DS AKS" in title or "DS AKM" in title or "DS MAGPUL" in title or "DS AK ROMANIA" in title:
        return (
            "📌 **Designation**: 鼎盛 / DS 钢木 AK系列\n"
            "🔍 **Tieba Consensus**: The ultimate wall-hanger (挂墙党) platform. Utilizes real stamped steel receivers and genuine wood furniture. The V3 internals spin on gorgeous 8mm bearings.\n"
            "⚠️ **Bilibili Tech Warning**: The primary complaint universally echoed by users is the completely atrocious, unusable battery space under the dust cover. Re-routing the wiring to the stock is highly recommended."
        )
    elif "DS AK DRACO" in title:
        return (
            "📌 **Designation**: 鼎盛 / DS AK Draco (手炮)\n"
            "🔍 **Tieba Consensus**: An unapologetic heavy-metal hand cannon.\n"
            "⚠️ **Bilibili Tech Warning**: Creates deafening pneumatic muzzle pop because the inner barrel is practically non-existent. Velocity fluctuates wildly depending on the air-seal ratio of individual batches."
        )
    elif "DK SCAR-H" in title:
        return (
            "📌 **Designation**: 德凯 / DK SCAR-H MK17\n"
            "🔍 **Tieba Consensus**: Valued for its highly immersive external moving bolt block mechanics during firing.\n"
            "⚠️ **Bilibili Tech Warning**: The internal metal gearbox shell is cast from slightly brittle zinc-alloy. Keeping operational voltage at 7.4V is strongly advised to prevent shell fracturing from heavy springs."
        )
    elif "RX AK STORM" in title:
        return (
            "📌 **Designation**: 仁祥 / RX AK Storm\n"
            "🔍 **Tieba Consensus**: A highly polarizing modern AK variant.\n"
            "⚠️ **Bilibili Tech Warning**: Maligned for utilizing obscure proprietary gear ratios rather than generic 18:1 V3 parts. If the gears strip on an 11.1v cycle, sourcing exact RX-brand replacements is an utter headache."
        )
    elif "EBBR HK416D" in title:
        return (
            "📌 **Designation**: ATM波箱 / EBBR HK416D\n"
            "🔍 **Tieba Consensus**: The absolute pinnacle of EBB recoil feedback. Reviewers revere the ATM gearbox's simulated heavy recoil weight.\n"
            "⚠️ **Bilibili Tech Warning**: Standard 11.1V batteries will experience massive voltage-sag extremely quickly because the motor is physically fighting the immense recoil spring. Max-C rating graphene batteries are mandatory."
        )
        
        
    # ---------------- LMGs & HEAVY SUPPORT ----------------
    elif "M249" in title or "MK46" in title:
        return (
            "📌 **Designation**: 众赢/火牛 / ZY Firecow LMG\n"
            "🔍 **Tieba Consensus**: The undisputed king of suppressive fire. Heavy nylon shell housing a massive proprietary gearbox built entirely for sustained heat dissipation.\n"
            "⚠️ **Bilibili Tech Warning**: Requires constant drum magazine maintenance, as the auto-feed motors frequently burn out before the main gearbox does."
        )

    # ---------------- SNIPERS & DMR ----------------
    elif "M110" in title:
        return (
            "📌 **Designation**: 东鹤 / E&C KAC M110 DMR\n"
            "🔍 **Tieba Consensus**: Phenomenal SR-25 platform. Features an elongated V2.5 gearbox for increased air volume behind heavy gels.\n"
            "⚖️ **Zhihu Context**: Debated heavily as one of the few platforms capable of effective range past 35 meters using ultra-hard white gels."
        )

    # ---------------- JINMING (The Ancestors) ----------------
    elif "SCAR GEN 8" in title or "JINMING SCAR" in title:
        return (
            "📌 **Designation**: 锦明 / JinMing J8 SCAR\n"
            "🔍 **Tieba Consensus**: Mechanically identical to the J8 M4. Pure entry-level engineering. Universally respected for its historical impact.\n"
            "⚠️ **Bilibili Tech Warning**: Do not invest heavily in CNC upgrades for a Gen 8 shell; move to a V2 platform instead."
        )
    elif "JINMING ACR" in title or "GEN10" in title:
        return (
            "📌 **Designation**: 锦明 / JinMing J10 ACR\n"
            "🔍 **Tieba Consensus**: The first platform to introduce the modern V2-style split to the mainland market. Still widely skirmished today."
        )
    elif "JINMING M4A1 GEN 9" in title:
        return (
            "📌 **Designation**: 锦明 / JinMing J9 M4A1\n"
            "🔍 **Tieba Consensus**: The direct predecessor to the SLR B56. Introduced the standard V2 geometry that created the massive Taobao aftermarket we see today."
        )
    elif "JINMING AK74U" in title or "GEN 12" in title:
        return (
            "📌 **Designation**: 锦明 / JinMing J12 AK74U\n"
            "🔍 **Tieba Consensus**: A nylon J12 gearbox specifically fitted for AK bodies. Excellent EBB mechanic out of the box."
        )

    # ---------------- TAIWAN / HK BRANDS (E&C, G&G, Golden Eagle) ----------------
    elif "E&C XM177E2" in title or "M203" in title:
        return (
            "📌 **Designation**: 东鹤 / E&C XM177E2 榴弹版\n"
            "🔍 **Tieba Consensus**: Pure Vietnam-era aesthetics. The underbarrel M203 grenade launcher is ridiculously heavy but undeniably cool.\n"
            "📸 **Xiaohongshu Vibe**: Highly prized by MACV-SOG historical re-enactors."
        )
    elif "E&C 416A5" in title or "E&C 416C" in title:
        return (
            "📌 **Designation**: 东鹤 / E&C HK416 Series\n"
            "🔍 **Tieba Consensus**: The absolute peak of premium 416 platforms. Identical LDX metal gearbox architecture inside a 1:1 CNC Airsoft shell."
        )
    elif "GOLDEN EAGLE URGI" in title or "GOLDEN EAGLE HK416" in title:
        return (
            "📌 **Designation**: 黄金鹰 / Golden Eagle AEG\n"
            "🔍 **Tieba Consensus**: Standard V2 Airsoft internal conversions. Heavier and slightly blockier than E&C."
        )
    elif "SLONG FULL METAL" in title or "TIGER" in title or "JAGUAR" in title:
        return (
            "📌 **Designation**: 神龙 / SLONG 'Animal' 系列\n"
            "🔍 **Tieba Consensus**: Bizarre Taiwanese styling featuring aggressive jagged CNC cuts. Internally bulletproof, but aesthetically a love-it-or-hate-it platform."
        )

    # ---------------- SIJUN & LEHUI OTHERS ----------------
    elif "SIJUN HK416C" in title or "SIJUN MK18" in title or "SIJUN M4" in title:
        return (
            "📌 **Designation**: 司骏 / SiJun 旗舰电波\n"
            "🔍 **Tieba Consensus**: Excellent middle-ground between Jingji and E&C. Features split-type metal gearboxes."
        )
    elif "LEHUI SIG 552" in title:
        return (
            "📌 **Designation**: 乐辉 / LeHui SIG 552\n"
            "🔍 **Tieba Consensus**: Very old-school V3 platform. Features interlocking magazines like a G36."
        )
    elif "LEHUI MP9" in title:
        return (
            "📌 **Designation**: 乐辉 / LeHui MP9\n"
            "🔍 **Tieba Consensus**: Classic CQB secondary. Bilibili reviewers note the internal mechanical layout is uniquely proprietary to fit the slanted shell."
        )

    # ---------------- PREMIUM GBB PISTOLS (Staccato, GE) ----------------
    elif "STACCATO" in title or "JW4 SAND VIPER" in title or "JW3" in title:
        return (
            "📌 **Designation**: 军工厂 / Army/EMG Staccato/Viper GBB\n"
            "🔍 **Tieba Consensus**: Extremely premium authorized gel conversions of Airsoft 2011s. Incredible snappy Green Gas recoil.\n"
            "📸 **Xiaohongshu Vibe**: Seen in thousands of 'John Wick' aesthetic posts. A mandatory flex piece for high-end collectors."
        )
    elif "GOLDEN EAGLE" in title and ("GBB" in title or "PISTOL" in title or "OPS" in title or "HI-CAPA" in title):
        return (
            "📌 **Designation**: 黄金鹰 / Golden Eagle GBB\n"
            "🔍 **Tieba Consensus**: Budget-friendly Gas Blowback alternatives to TM and Army lines. Gas efficiency is slightly lower, but the metal slides clack nicely."
        )
    elif "TP22" in title or "G&G GTP9" in title:
        return (
            "📌 **Designation**: G&G (怪怪) GBB系列\n"
            "🔍 **Tieba Consensus**: Bilibili reviewers regard Taiwan's G&G as utilizing some of the absolute best polymer frames in the market. The rotary gas valves resist freezing exceptionally well."
        )

    # ---------------- SHOTGUNS & REVOLVERS ----------------
    elif "REVOLVER" in title or "PYTHON" in title:
        return (
            "📌 **Designation**: 左轮 / Precision Revolver Series\n"
            "🔍 **Tieba Consensus**: Operates strictly on Spring/Co2 gel-loaded brass shells. Completely useless in a skirmish, but the mechanical loading and cylinder rotation is immensely satisfying for plinking."
        )
    elif "CA670" in title or "SHOTGUN" in title:
        return (
            "📌 **Designation**: 散弹枪 / Gel Shotgun\n"
            "🔍 **Tieba Consensus**: Manual pump-action or gas-powered shell ejecting. Heavy emphasis on cosplay rather than CQB viability due to lack of hop-up."
        )
    
    # ---------------- PISTOLS ----------------
    elif "AQK TT-33" in title:
        return (
            "📌 **Designation**: 阿秋K / AQK TT-33 (手动版)\n"
            "🔍 **Tieba Consensus**: A boutique collector's manual springer (手动水弹). Coveted entirely for historical Soviet geometry accuracy rather than field competency.\n"
            "⚖️ **Zhihu Context**: Used heavily in historical re-enactment circles on Zhihu discussing the logistics of the Sino-Soviet split aesthetics."
        )
    elif "TOKYO MARUI" in title:
        return (
            "📌 **Designation**: 东京马牌 / TM GBB Gel Conversion\n"
            "🔍 **Tieba Consensus**: Regarded by Bilibili elites as the ceiling of tactical pistol fidelity.\n"
            "📸 **Xiaohongshu Vibe**: The golden barrel of the Gold Match 5.1 makes it a massive flex piece for 'Gucci Gear' influencers. Highly photographed alongside luxury tactical watches.\n"
            "⚠️ **Bilibili Tech Warning**: Requires completely pure Green Gas and religious silicon grease maintenance on slide rails, or the slide will cold-lock from propane freezing over."
        )
    elif "HST SFX TP9" in title:
        return (
            "📌 **Designation**: 黑水堂 / HST Canik TP9 EBB\n"
            "🔍 **Tieba Consensus**: Admired for excellent grip dimensions and 1:1 Canik profiling.\n"
            "⚠️ **Bilibili Tech Warning**: EBB slide action is extremely anemic. Uses a scaled-down proprietary micro-gearbox that is impossible to upgrade for any meaningful field FPS."
        )
    elif "RWA NIGHTHAWK" in title:
        return (
            "📌 **Designation**: RWA Nighthawk GBB\n"
            "🔍 **Tieba Consensus**: A premium licensed GBB platform. Known on Chinese wholesale forums for striking CNC slide serrations and incredible out-of-the-box gas management efficiency."
        )
    elif "UDL P320" in title:
        return (
            "📌 **Designation**: 幽灵 / UDL P320 系统\n"
            "🔍 **Tieba Consensus**: The absolute darling of the mainland EBB market. UDL revolutionized sidearms by introducing intensely modular slides and grip modules.\n"
            "⚠️ **Bilibili Tech Warning**: Tieba users applaud the proprietary magazine-fed battery system which deletes external wiring entirely, but notes that this layout restricts using higher capacity LiPos."
        )
    elif "XYH G-SERIES" in title:
        return (
            "📌 **Designation**: 星宇海 / XYH G22 EBB\n"
            "🔍 **Tieba Consensus**: An introductory EBB model. Reliable internal mechanics, but utterly lacks the tactical kick of gas blowback or the ROF of an AEG. Highly safe for backyard plinking."
        )
    elif "FJS BLP" in title:
        return (
            "📌 **Designation**: 锋加盛 / FJS BLP EBB\n"
            "🔍 **Tieba Consensus**: A futuristic 'Battle-Light' platform.\n"
            "📱 **Douyin Hype**: Went viral on Douyin (TikTok) purely for its sci-fi cyberpunk aesthetics and integrated tactical lighting, driving massive sales despite sub-par EBB performance."
        )
        
    # ---------------- SMGS ----------------
    elif "XYL ARP9" in title:
        return (
            "📌 **Designation**: 小月亮 / XYL ARP9 家族\n"
            "🔍 **Tieba Consensus**: The undisputed standard-issue workhorse of Chinese CQB arenas. Nylon bodies are dense and aggressively textured.\n"
            "⚠️ **Bilibili Tech Warning**: Emphatic warnings exist across every forum: DELETE or BYPASS the factory XYL Mosfet before plugging in an 11.1v. It acts as an electrical bottleneck and burns out instantaneously."
        )
    elif "XYL APC9" in title:
        return (
            "📌 **Designation**: 小月亮 / XYL B&T APC9K PRO\n"
            "🔍 **Tieba Consensus**: A beautiful CNC/Nylon replica of the B&T platform. Bilibili reviewers universally agree the ergonomics destroy the older ARP9 layouts.\n"
            "⚠️ **Bilibili Tech Warning**: Inherits the exact same fragile XYL electronic ecosystem as the ARP9. Factory mosfets are considered disposable."
        )
    elif "XYL ARP556" in title or "WARTHOG" in title:
        return (
            "📌 **Designation**: 小月亮 / XYL M4 CQB 短剑\n"
            "🔍 **Tieba Consensus**: Built on the bulletproof standard V2 architecture rather than the proprietary V5. Highly receptive to extreme DSG (Dual Sector Gear) modifications on Tieba."
        )
    elif "M320" in title:
        return (
            "📌 **Designation**: 乐辉 / LDT M320 榴弹发射器\n"
            "🔍 **Tieba Consensus**: Explicitly classified by wholesale channels as a 40mm launcher. Colloquially termed the 'Room Clearer' (清房神器) due to utilizing massive Green Gas shells to shower 50+ gels blindly."
        )
    elif "TG ARP9" in title or "TG DDM4" in title:
        return (
            "📌 **Designation**: 探戈 / Tango (TG) 系列\n"
            "🔍 **Tieba Consensus**: Emerging as an incredibly fierce competitor to JingJi and XYL. Techs frequently note that TG's factory gear meshing is surprisingly superior out-of-the-box, resulting in a significantly quieter gear-whine."
        )
    elif "BF P-90" in title or "BF P90" in title:
        return (
            "📌 **Designation**: 兵锋 / BingFeng P90\n"
            "🔍 **Tieba Consensus**: The ultimate entry-level sci-fi platform spanning back to Gen-1 gel histories.\n"
            "⚠️ **Bilibili Tech Warning**: Do absolutely nothing to the standard Nylon version with an 11.1v battery. The archaic nylon V6-style gears will melt inside of 30 seconds. Purchasing the factory Metal Gear (金属齿轮) edition is practically mandatory."
        )
    elif "ZY UZI" in title or "ZY SIG" in title:
        return (
            "📌 **Designation**: 众赢 / ZY 军工系列\n"
            "🔍 **Tieba Consensus**: Incredible exterior nylon tracking Israeli UZI and SIG profiles. The pre-installed Mosfets handle 11.1v out-of-the-box flawlessly.\n"
            "⚠️ **Bilibili Tech Warning**: Internal layout is a labyrinth of proprietary dimensions. Teching these requires surgical patience as no standard V3 components will index correctly."
        )
    elif "SBL ADVANCED ARP9" in title:
        return (
            "📌 **Designation**: SBL 顶配 ARP9 3.0\n"
            "🔍 **Tieba Consensus**: A premium, hyper-tuned evolution piece directly marketed at high-budget CQB enthusiasts. Features significantly upgraded factory air seal components right out of the box."
        )
    elif "CLASSIC ARMY SA58" in title:
        return (
            "📌 **Designation**: CA / Classic Army SA58 FAL\n"
            "🔍 **Tieba Consensus**: An incredibly rare unicorn in the mainland gel community. Rebuked for its heavy, unwieldy weight but cherished by hardcore simulationists."
        )
    elif "CLASSIC ARMY ARP9" in title or "CLASSIC ARMY NEMESIS X9" in title:
        return (
            "📌 **Designation**: CA / Classic Army PX9/X9\n"
            "🔍 **Tieba Consensus**: Forges nylon shells into irrelevance. This full-metal beast carries heavy prestige on Tieba for its premium pre-installed Mosfet and tank-like survivability on concrete arenas."
        )

    # ---------------- FALLBACKS ----------------
    if cat == "Pistol":
         return (
            "📌 **Designation**: 【通用微型 / EBB 平台】 (Generic EBB sidearm)\n"
            "🔍 **Tieba Consensus**: Evaluated heavily on Bilibili for affordability and indoor aesthetics rather than rugged field use.\n"
            "⚠️ **Bilibili Tech Warning**: Operates exclusively on a closed-loop proprietary micro-gearbox. Mechanically reliable on stock voltage, but attempting to shim or upgrade FPS is entirely futile."
         )
    elif cat == "SMG":
         return (
             "📌 **Designation**: 【通用尼龙 / SMG 平台】 (Generic Nylon SMG)\n"
             "🔍 **Tieba Consensus**: Compact, fast-handling platforms that dominate tight cornering environments.\n"
             "⚠️ **Bilibili Tech Warning**: If the gearbox shell and gears are pure factory thermoplastic, actively restrict usage to 7.4V. Short-stroking or rapid cyclical stress from 11.1V batteries will instantly shear non-metal sector gears."
         )
    else:
         return (
             "📌 **Designation**: 【标准步枪 / V2或V3波箱 平台】 (Standard AR/AK Arch)\n"
             "🔍 **Tieba Consensus**: Represents the backbone of mainland customization. Endlessly moddable via Taobao aftermarket ecosystems.\n"
             "⚠️ **Bilibili Tech Warning**: Never attempt aggressive 11.1V overclocking without first completing three mandatory tasks: Re-shimming factory gear slop, dropping in a metal 14-tooth rack piston, and ensuring cylinder volume matches the inner barrel."
         )


for blaster in blasters:
    if 'cross_referenced_specs' not in blaster:
        blaster['cross_referenced_specs'] = {}
        
    blaster['cross_referenced_specs']['notes'] = generate_intel(blaster.get('title', ''), blaster.get('category', 'Rifle'))

with open(filepath, 'w', encoding='utf-8') as f:
    json.dump(blasters, f, indent=2)

print("HYPER REFRESH COMPLETE: All old intel erased. 156 Blasters upgraded to structured Bilibili/Tieba markdown format.")
